import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";
import { PreviewBridge } from "@/components/preview-bridge";
import { PreviewToolbarLoader } from "@/components/preview-toolbar-loader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          {/* Mounted at the root so every route group can raise a toast. It
              used to live only in `app/admin/layout.tsx`, which meant a
              `toast()` anywhere else — the whole `(app)` group — rendered
              nothing: the call succeeded, the action behind it succeeded, and
              the user saw silence. A spec written against that feedback fails
              for a reason that has nothing to do with the feature under test.
              One Toaster, at the root, is also what the styleguide page has
              always told readers this template does. */}
          <Toaster />
          {/* The preview's half of the postMessage bridge: it tells the Epic
              workspace where this frame is, and answers its two questions.
              Inert outside an iframe. Removing it blanks the workspace's
              address bar and breaks screen switching — see
              docs/references/preview-bridge.md in the prototype template. */}
          <PreviewBridge />
          {/* Pulls the annotation toolbar from the workspace that framed this
              preview. Unlike the bridge above, this one is safe to delete: the
              app works without it, and the toolbar it loads is served by
              Epic rather than living here — which is how a machine built from
              an old snapshot can still receive a fixed one. */}
          <PreviewToolbarLoader />
        </Providers>
      </body>
    </html>
  );
}
